# .github/workflows/test.yml
name: test
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 2
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 20s
  first_parallel:
    runs-on: ubuntu-latest  
    needs: hello
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 20s
  second_parallel:
    runs-on: ubuntu-latest  
    needs: hello
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 20s          
  third_parallel:
    runs-on: ubuntu-latest  
    needs: hello
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 10s
  fourth_parallel:
    runs-on: ubuntu-latest  
    needs: hello
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 10s   
  fifth_parallel:
    runs-on: ubuntu-latest  
    needs: hello
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 10s 
  bye:
    runs-on: ubuntu-latest  
    needs: [first_parallel, second_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s              
  bye_bye:
    runs-on: ubuntu-latest  
    needs: [third_parallel, bye] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s    
  bye_bye_bye:
    runs-on: ubuntu-latest  
    needs: [fourth_parallel, bye_bye] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s    
  bye_1:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s  
  bye_2:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s 
  bye_3:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s      
  bye_4:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s  
  bye_5:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s 
  bye_6:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s           
  bye_7:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s  
  bye_8:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s            
  bye_9:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s  
  bye_10:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s 
  bye_11:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s      
  bye_12:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s  
  bye_13:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s 
  bye_14:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s           
  bye_15:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s  
  bye_16:
    runs-on: ubuntu-latest  
    needs: [first_parallel] 
    steps:
      - name: Bye
        id: bye
        run: |
          echo "Bye world"
          sleep 10s 
