# .github/workflows/test.yml
name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 2
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 20s
      - name: parallel first
        if: steps.hello.outcome == 'success'
        run: |
          echo "first parallel step"
          sleep 20
      - name: parallel second
        if: steps.hello.outcome == 'success'
        run: |
          echo "second parallel step"
          sleep 20        
      - name: Bye
        run: |
          echo "Bye world"
          sleep 10s      
  first_parallel:
    runs-on: ubuntu-latest  
    needs: test
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 20s
  second_parallel:
    runs-on: ubuntu-latest  
    needs: test
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello world"
          sleep 20s          
